apiVersion: apps/v1
kind: Deployment
metadata:
  name: locker-services-deployment
  namespace: express
  labels:
    app: locker-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locker-services
  template:
    metadata:
      labels:
        app: locker-services
    spec:
      containers:
        - name: locker-services
          image: registry.cn-shenzhen.aliyuncs.com/danielvt/vt:Locker_Services-v1.0
          ports:
            - containerPort: 8200
---
apiVersion: v1
kind: Service
metadata:
  name: locker-k8s-service
spec:
  selector:
    app: locker-services
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8200