spring:
  application:
    name: Account_Services
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://free-tier.gcp-us-central1.cockroachlabs.cloud:26257/defaultdb?user=vt&password=BkMStCN_Fd4Mu8tr&sslmode=verify-full&sslrootcert=crdb.crt&options=--cluster=hairy-zebra-1673&TimeZone=Asia/Shanghai
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.lingnan.dto
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8100

logging:
  level:
    cn.lingnan: debug