apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-services-deployment
  namespace: express
  labels:
    app: account_services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-services
  template:
    metadata:
      labels:
        app: account-services
    spec:
      containers:
        - name: account-services
          image: registry.cn-shenzhen.aliyuncs.com/danielvt/vt:Account_Services-v1.0
          ports:
            - containerPort: 8100
---
apiVersion: v1
kind: Service
metadata:
  name: account-k8s-service
spec:
  selector:
    app: account-services
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8100
