spring:
  application:
    name: Locker_Services
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:26257/els_locker
    username: root
    password: 456987
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8200

logging:
  level:
    cn.lingnan: debug