spring:
  application:
    name: Locker_Services
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgres://vt:BkMStCN_Fd4Mu8tr@free-tier.gcp-us-central1.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full&sslrootcert=crdb_cert/cc-ca.crt&options=--cluster=hairy-zebra-1673
    username: root
    password: 456987
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8200

logging:
  level:
    cn.lingnan: debug