spring:
  application:
    name: Package_Services
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://free-tier.gcp-us-central1.cockroachlabs.cloud:26257/defaultdb?user=vt&password=BkMStCN_Fd4Mu8tr&sslmode=verify-full&sslrootcert=E:\\cc-ca.crt&options=--cluster=hairy-zebra-1673
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8300

logging:
  level:
    cn.lingnan: debug