DROP TABLE IF EXISTS els_acc.WEB_ACCOUNT;
CREATE TABLE els_acc.WEB_ACCOUNT
(
    ID          INT DEFAULT UNIQUE_ROWID() PRIMARY KEY,
    USERNAME    VARCHAR(20),
    PASSWORD    VARCHAR(20),
    PHONE       VARCHAR(20),
    STATUS      INT,
    EXP_TIME    TIMESTAMPTZ(0),
    CREATE_TIME TIMESTAMPTZ(0),
    UPDATE_TIME TIMESTAMPTZ(0),
    STATUS_TIME TIMESTAMPTZ(0),
    AUTHORITY   VARCHAR(200),
    REMARK      VARCHAR(200)
)