DROP TABLE IF EXISTS els_package.PACKAGE_INFORMATION;
CREATE TABLE els_package.PACKAGE_INFORMATION
(
    PACKAGE_ID         INT DEFAULT UNIQUE_ROWID() PRIMARY KEY,
    EXPRESS_NUMBER     VARCHAR(20),
    EXPRESS_COMPANY    INT,
    RECEIVER_PHONE     VARCHAR(20),
    RECEIVER_ADDRESS   VARCHAR(200),
    RECEIVER_NAME      VARCHAR(10),
    SENDER_NAME        VARCHAR(10),
    SENDER_PHONE       VARCHAR(20),
    SENDER_ADDRESS     VARCHAR(200),
    EXP_OPERATOR_ID    INT,
    EXP_OPERATOR_PHONE VARCHAR(11),
    CREATE_TIME        TIMESTAMPTZ(0),
    UPDATE_TIME        TIMESTAMPTZ(0),
    STATUS_TIME        TIMESTAMPTZ(0),
    STATUS             INT,
    REMARK             VARCHAR(200)
);

DROP TABLE IF EXISTS els_package.package_box_information;
CREATE TABLE els_package.PACKAGE_BOX_INFORMATION
(
    PBI_ID        UUID DEFAULT GEN_RANDOM_UUID() PRIMARY KEY,
    PACKAGE_ID    INT,
    LOCKER_ID     INT,
    LOCKER_BOX_ID UUID,
    PACKAGE_CODE  VARCHAR(10),
    OPERATOR_ID   VARCHAR(200),
    CREATE_TIME   TIMESTAMPTZ(0),
    UPDATE_TIME   TIMESTAMPTZ(0),
    STATUS_TIME   TIMESTAMPTZ(0),
    STATUS        INT,
    REMARK        VARCHAR(200)
);